CREATE TABLE USERS (
    USER_ID CHAR(10) ,
    EMAIL VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    PHONE DECIMAL(10,0),
    PROFILE_IMAGE VARCHAR(255),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    PRIMARY KEY (USER_ID)
    );

CREATE TABLE BUYER (
    BUYER_ID CHAR(10) ,
    BILLING_ADDRESS VARCHAR(255),
    SHIPPING_ADDRESS VARCHAR(255),
    PRIMARY KEY(BUYER_ID)
);

CREATE TABLE SELLER(
    SELLER_ID CHAR(10) ,
    SELLER_ADDRESS VARCHAR(255),
    COMPANY_NAME VARCHAR(255) NOT NULL,
    ACCOUNT_NUMBER INT NOT NULL,
    ROUTING_NUMBER INT NOT NULL,
    PRIMARY KEY (SELLER_ID)
);

CREATE TABLE ITEMS(
    ITEM_ID CHAR(25) ,
    ITEM_NAME VARCHAR(255) NOT NULL,
    ITEM_DESCRIPTION VARCHAR(255),
    SELLER_ID CHAR(10) NOT NULL,
    IS_SOLD NUMBER(1) DEFAULT 0,
    IMAGE VARCHAR(255),
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE NORMAL_ITEM(
    ITEM_ID CHAR(25) ,
    PRICE FLOAT NOT NULL,
    AVAILABLE_QUANTITY INT DEFAULT 1,
    PRIMARY KEY (ITEM_ID) 
);

CREATE TABLE AUCTION_ITEM(
    ITEM_ID CHAR(25),
    AUCTION_ID CHAR(25),
    PRIMARY KEY (ITEM_ID, AUCTION_ID)    
);

CREATE TABLE AUCTION_DETAIL(
    AUCTION_ID CHAR(25),
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_TIME TIMESTAMP NOT NULL,
    MIN_INCREMENT_PRICE FLOAT NOT NULL,
    START_PRICE FLOAT NOT NULL,
    END_PRICE FLOAT NOT NULL,
    PRIMARY KEY (AUCTION_ID)
);

CREATE TABLE PAYMENT_DETAILS(
    PD_ID CHAR(10) ,
    BUYER_ID CHAR(10) NOT NULL,
    CREDIT_CARD INT,
    ACCOUNT_NUMBER INT,
    ROUTING_NUMBER INT,
    PRIMARY KEY (PD_ID)
);

CREATE TABLE BID(
    BID_ID CHAR(25) ,
    BID_TIMESTAMP TIMESTAMP NOT NULL,
    BID_PRICE FLOAT NOT NULL,
    BUYER_ID CHAR(10) NOT NULL,
    ITEM_ID CHAR(25) NOT NULL,
    AUCTION_ID CHAR(25) NOT NULL,
    PRIMARY KEY (BID_ID)
);

CREATE TABLE WISHLIST(
    WISHLIST_ID CHAR(10),
    TOTAL_ITEMS INT,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (WISHLIST_ID)
);

CREATE TABLE ADDED_TO_WISHLIST(
    WISHLIST_ID CHAR(10),
    ITEM_ID CHAR(25),
    PRIMARY KEY (WISHLIST_ID,ITEM_ID)
);

CREATE TABLE CART(
    CART_ID CHAR(10) ,
    TOTAL_ITEMS INT,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (CART_ID)
);

CREATE TABLE ADDED_TO_CART(
    CART_ID CHAR(10),
    ITEM_ID CHAR(25),
    PRIMARY KEY(CART_ID, ITEM_ID)
);


CREATE TABLE REVIEW(
    REVIEW_ID CHAR(25) , 
    RATING FLOAT NOT NULL CHECK (RATING>=0 AND RATING <=5),
    REVIEW_COMMENT VARCHAR(255),
    ITEM_ID CHAR(25) NOT NULL,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (REVIEW_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID CHAR(25) ,
    ORDER_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE NORMAL_ITEM_ORDER(
    ORDER_ID CHAR(25),
    ITEM_ID CHAR(25),
    PURCHASED_QUANTITY INT DEFAULT 1, 
    PRIMARY KEY(ORDER_ID,ITEM_ID)
);

CREATE TABLE AUCTION_ORDER(
    AUCTION_ORDER_ID CHAR(25),
    AUCTION_ID CHAR(25) NOT NULL,
    ITEM_ID CHAR(25) NOT NULL,
    AUCTION_ORDER_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BUYER_ID CHAR(10) NOT NULL,
    PRIMARY KEY (AUCTION_ORDER_ID)
);

CREATE TABLE PAYMENT(
    TRANSACTION_ID CHAR(25) ,
    REFERENCE_NUMBER INT NOT NULL,
    CARD_NUMBER INT NOT NULL,
    AMOUNT FLOAT NOT  NULL,
    PAYMENT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ORDER_ID CHAR(25) NOT NULL,
    AUCTION_ORDER_ID CHAR(25) NOT NULL,
    PRIMARY KEY (TRANSACTION_ID)
);


ALTER TABLE SELLER ADD CONSTRAINT SELLER_FK FOREIGN KEY(SELLER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE;
        
ALTER TABLE BUYER ADD CONSTRAINT BUYER_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE; 

ALTER TABLE ITEMS ADD CONSTRAINT ITEM_SELLER_FK FOREIGN KEY(SELLER_ID) 
        REFERENCES SELLER(SELLER_ID) ON DELETE CASCADE; 

ALTER TABLE NORMAL_ITEM ADD CONSTRAINT ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE; 


ALTER TABLE AUCTION_ITEM ADD CONSTRAINT AUCTION_ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE; 



ALTER TABLE AUCTION_ITEM ADD CONSTRAINT AUCTION_ITEM_AUCTION_ID_FK FOREIGN KEY(AUCTION_ID) 
        REFERENCES AUCTION_DETAIL(AUCTION_ID) ON DELETE CASCADE;

ALTER TABLE PAYMENT_DETAILS ADD CONSTRAINT PAYMENT_DETAILS_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE BID ADD CONSTRAINT BID_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE BID ADD CONSTRAINT BID_AUCTION_ITEM_ID_FK FOREIGN KEY(AUCTION_ID,ITEM_ID) 
        REFERENCES AUCTION_ITEM(AUCTION_ID,ITEM_ID) ON DELETE CASCADE;


ALTER TABLE WISHLIST ADD CONSTRAINT WISHLIST_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE ADDED_TO_WISHLIST ADD CONSTRAINT WISHLIST_ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE;


ALTER TABLE ADDED_TO_WISHLIST ADD CONSTRAINT WISHLIST_ID_FK FOREIGN KEY(WISHLIST_ID) 
        REFERENCES WISHLIST(WISHLIST_ID) ON DELETE CASCADE;


ALTER TABLE CART ADD CONSTRAINT CART_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE ADDED_TO_CART ADD CONSTRAINT CART_ID_FK FOREIGN KEY(CART_ID) 
        REFERENCES CART(CART_ID) ON DELETE CASCADE;


ALTER TABLE ADDED_TO_CART ADD CONSTRAINT CART_ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE;


ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE;


ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE NORMAL_ITEM_ORDER ADD CONSTRAINT NORMAL_ITEM_ID_FK FOREIGN KEY(ITEM_ID) 
        REFERENCES ITEMS(ITEM_ID) ON DELETE CASCADE;


ALTER TABLE NORMAL_ITEM_ORDER ADD CONSTRAINT NORMAL_ORDER_ID_FK FOREIGN KEY(ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE;


ALTER TABLE AUCTION_ORDER ADD CONSTRAINT AUCTION_ORDER_BUYER_ID_FK FOREIGN KEY(BUYER_ID) 
        REFERENCES BUYER(BUYER_ID) ON DELETE CASCADE;


ALTER TABLE AUCTION_ORDER ADD CONSTRAINT AUCTION_ORDER_ITEM_ID_FK FOREIGN KEY(AUCTION_ID,ITEM_ID) 
        REFERENCES AUCTION_ITEM(AUCTION_ID,ITEM_ID) ON DELETE CASCADE;


ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_ORDER_ID_FK FOREIGN KEY(ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE;

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_AUCTION_ORDER_ID_FK FOREIGN KEY(AUCTION_ORDER_ID) 
        REFERENCES AUCTION_ORDER(AUCTION_ORDER_ID) ON DELETE CASCADE;
