
SELECT * FROM USERS;
SELECT * FROM BUYER;
SELECT * FROM SELLER;
SELECT * FROM ITEMS;
SELECT * FROM ORDERS;
SELECT * FROM NORMAL_ITEM;
SELECT * FROM NORMAL_ITEM_ORDER;
SELECT * FROM AUCTION_ITEM;
SELECT * FROM AUCTION_DETAIL;
SELECT * FROM AUCTION_ORDER;
SELECT * FROM PAYMENT;